namespace nilnul.geometry.linear
{
	/// <summary>
	/// the line segment between two points. it's directionless.
	/// This is the encircled area of two points that forms a cloze/bound.
	/// So this is 2d objected generated by two 1d object.
	/// </summary>
	/// alias:
	///		tend
	///			like in tender
	///				or tendon
	///		tread
	///			like treadmill
	///		lace
	///		slip
	///		join
	///		bind
	///		weld
	///		knot
	///		knit
	///		tie
	///		link
	///		reach
	///		seg
	///		span
	///		lump
	///		wad
	///		wade
	///		pace
	public interface ITend : ITope, ITrace
	{

	}
}
