using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace nilnul.num.complex.matrix_.sym_.vandermonde_.cycle
{
	/// <summary>
	/// multiply the fourier transform matrix generated by E(tau/n) with a colwise complex number vector, and we get the result.
	/// ifft is same process but with the inversed matrix, which uses the omega as 1/n E(-tau/n)
	/// </summary>
	class DiscreteFourierTransform
	{

	}
}
